### ISSUE TITLE
数字和文字在一起不行

### ISSUE THREAD

**Issue by JiYJCoder** [Kuaizi-co/kz-table#4]
![image](https://user-images.githubusercontent.com/22410768/53721373-0f106b80-3e9e-11e9-8926-2fc03bbf2981.png)

**Comment by JiYJCoder** [comment]
不止这样，还有一些列也不会自动宽度

**Comment by JiYJCoder** [comment]
找到问题了。有些数据我是加了按钮或者是一些处理过的数据，就不能正常的计算出宽度

**Comment by tomieric** [comment]
@JiYJCoder 这是个只支持纯文字版
