### ISSUE TITLE
可以增加列最大宽度的配置吗？

### ISSUE THREAD

**Issue by zhuxulu** [Kuaizi-co/kz-table#7]
## 项目版本
~ 2.0.10

## 操作系统版本 / 浏览器版本
~ 

## Vue 版本
~ 

## 重现链接
~ 

## 重现步骤
~

## 期待的行为
~

## 实际的行为
~

**Comment by zhuxulu** [comment]
谢谢，npm啥时候更新啊？

**Comment by tomieric** [comment]
发布源有些问题，现在已解决发到 npm 上。版本是`3.x`
